API mock server
line/clova-chatbot-web-kit pull request #9
Opened 2022-05-17 05:52 UTC by naganoyasuaki

Added examples of 5.using-with-api-mock

2022-05-17 05:59 UTC, naganoyasuaki commented on examples/5.using-with-api-mock/index.html
> +    <script src="https://naganoyasuaki.github.io/clova-chatbot-web-kit/examples/1.getting-started/webchat-3.js"></script>
Should be replaced by CDN

2022-05-23 13:20 UTC, Ryo0o commented on examples/5.using-with-api-mock/index.html
> +    <script src="https://naganoyasuaki.github.io/clova-chatbot-web-kit/examples/1.getting-started/webchat-3.js"></script>
Does this not work with webchat.js currently deployed on the CDN?

2022-05-24 02:24 UTC, naganoyasuaki commented on examples/5.using-with-api-mock/index.html
> +    <script src="https://naganoyasuaki.github.io/clova-chatbot-web-kit/examples/1.getting-started/webchat-3.js"></script>
It works, but
https://github.com/line/clova-chatbot-web-kit/pull/7
is not included, so `ONLY NORMAL IMAGE` response is not displayed.

2022-05-24 02:27 UTC, naganoyasuaki commented on examples/5.using-with-api-mock/index.html
> +    <script src="https://naganoyasuaki.github.io/clova-chatbot-web-kit/examples/1.getting-started/webchat-3.js"></script>
<img width="359" alt="スクリーンショット 2022-05-24 11 26 39" src="https://user-images.githubusercontent.com/1168878/169936160-8e9589af-b777-4fc5-a7a1-14fcbf360a8f.png">

2022-05-26 00:55 UTC, Ryo0o commented on examples/5.using-with-api-mock/index.html
> +    <script src="https://naganoyasuaki.github.io/clova-chatbot-web-kit/examples/1.getting-started/webchat-3.js"></script>
I see.
I will release a new version of webchat.js and put it on the CDN.
Please wait a moment.

2022-05-26 11:17 UTC, Ryo0o commented on examples/5.using-with-api-mock/index.html
> +    <script src="https://naganoyasuaki.github.io/clova-chatbot-web-kit/examples/1.getting-started/webchat-3.js"></script>
I deployed new webchat.js as `webchat-1.2.0.js`
Please check it, and update this PR.

2022-05-26 11:21 UTC, Ryo0o requested changes
I deployed new webchat.js as webchat-1.2.0.js
Please check it, and update this PR.

2022-05-30 07:24 UTC, Ryo0o approved these changes
LGTM

2022-05-30 07:24 UTC, merged